<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AgendaMedicoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'titulo' => 'required|max:100',
            'start' => 'required',
            'end' => 'required',
            'descricao' => 'nullable|max:100|'
        ];
    }
    public function messages()
    {
        return [
            'titulo.required' => 'Esse campo precisa ser preenchido',
            'titulo.max' => 'Esse campo tem limite de 100 caracteres',

            'start.required' => 'Esse campo precisa ser preenchido',
            'end.required' => 'Esse campo precisa ser preenchido',

            'descricao.max' => 'Esse campo tem limite de 100 caracteres',
        ]; // TODO: Change the autogenerated stub
    }
}
