<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EspecialidadeRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'especialidade' => 'required|max:191',
            'descricao' => 'required|max:250',
        ];
    }

    public function messages()
    {
        return [
            'especialidade.requried' => 'O campo especialidade é obrigatório.',
            'especialidade.max' => 'O campo especialidade só aceita 190 caracteres.',

            'descricao.requried' => 'O campo descricao é obrigatório.',
            'descricao.max' => 'O campo descricao só aceita 250 caracteres.',
        ]; // TODO: Change the autogenerated stub
    }
}
