<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UsuarioResquest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'usuario' => ['required', 'string', 'max:255', 'unique:users'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8'],
            'confirm_passowrd' => 'required|same:password',

        ];
    }

    public function messages()
    {
        return [
            'usuario.required' => 'O campo usuário é obrigatório.',

            'email.required' => 'O campo email é obrigatório.',

            'password.required' => 'O campo password é obrigatório.',

            'confirm_passowrd.required' => 'O campo de confirmação de senha é obrigatório.',
            'confirm_passowrd.same' => 'O campo senha e confirma senha não coincidem.',

            'nome.required' => 'O campo nome é obrigatório.',



        ]; // TODO: Change the autogenerated stub
    }
}
