<?php

namespace App\Http\Requests\Servico;

use Illuminate\Foundation\Http\FormRequest;

class SolicitacaoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'especialidade_id' => 'required|exists:especialidades,id',
            'conselho' => 'required|string|max:100',
            'num_conselho' => 'required|string|max:100',
            'rqe' => 'required|string|max:100',

            'rg' => 'required|string|max:13',
            'telefone' => 'required_without_all:celular|telefone_com_ddd',
            'celular' => 'required_without_all:telefone|celular_com_ddd',

            'procedimento' => 'required|string|max:500',
        ];
    }

    public function messages()
    {
        return [
            'especialidade_id.required' => "O campo especialidade é obrigatório.",
            'especialidade_id.exists' => "O campo especialidade não existe em nosso banco.",
        ]; // TODO: Change the autogenerated stub
    }
}
